### ISSUE TITLE
MediaInfo.codecs  type  confuse

### ISSUE THREAD

**Issue by notedit** [medooze/semantic-sdp-js#10]
in this line  
https://github.com/medooze/semantic-sdp-js/blob/master/lib/MediaInfo.js#L159
the codecs type is Map<string, CodecInfo>

and in this  line  
https://github.com/medooze/semantic-sdp-js/blob/master/lib/MediaInfo.js#L151
the codes type is Map<int, CodecInfo>

we should make them the same.

**Comment by murillo128** [comment]
should be `Number`

**Comment by murillo128** [comment]
thanxs for spotting that out!

**Comment by notedit** [comment]
@murillo128  we should check this too    https://github.com/medooze/semantic-sdp-js/blob/f815d256b3719062987a2d29269563d117972ca1/lib/MediaInfo.js#L451 

CodecInfo.MapFromNames  still return  Map<string, CodecInfo>

**Comment by notedit** [comment]
https://github.com/medooze/semantic-sdp-js/blob/master/lib/MediaInfo.js#L177 

getCodec should return array or map too.   Chrome has three profiles for h264 codec.

**Comment by murillo128** [comment]
This would be backward incompatible, I would propose to add a new method with different name 
instead

**Comment by mildsunrise** [comment]
the issues mentioned here should've been fixed in #28 and #31.
for the getCodec() proposed change, please open a new issue :pray:
