### ISSUE TITLE
MediaInfo protocol and port ?!

### ISSUE THREAD

**Issue by egzonzeneli** [medooze/semantic-sdp-js#11]
Is there any reason why properties like `protocol` and `port `are being omitted on parsing and then only at `SDPInfo.toString` initializing with default values `{ port: 9, protocol: 'UDP/TLS/RTP/SAVPF' }`

**Comment by murillo128** [comment]
Because it is mean to be used in bundle with webrtc, so this values are superfluous

**Comment by egzonzeneli** [comment]
Got it. Thanks.
