### ISSUE TITLE
msid not defined

### ISSUE THREAD

**Issue by yelodevopsi** [medooze/semantic-sdp-js#20]
https://github.com/medooze/semantic-sdp-js/blob/371eb08d68a2707c25799e550985df03c534087d/lib/SDPInfo.js#L1546

I receive errors here with our production build. Seems like msid is set globally previously, but not always.

Declaring "var msid" fixes the problem if it is undefined.

I'm not able to find that msid is set globally elsewhere. Is this correct?

`
if (msid === undefined)
						var msid = streamId;
					else 
						msid = streamId;
`

**Comment by murillo128** [comment]
I can't find where the `msid` is used at all, must be a leftover. I have removed it and published a new version.

Thank you very much for the report!
