### ISSUE TITLE
add h264 profile-level-id limit

### ISSUE THREAD

**Issue by notedit** [medooze/semantic-sdp-js#7]
I see there is a packetization-mode limit,  no profile-level-id limit.
Firefox only support  profile-level-id 42e01f for now.

**Comment by notedit** [comment]
I have a fix in this   https://github.com/notedit/semantic-sdp-js/commit/6465703e57e06db0ab56b02e59ee96671edbd22d

**Comment by murillo128** [comment]
I will have to check it a bit more for side issues, but it looks good

**Comment by murillo128** [comment]
Thank you!
