### ISSUE TITLE
getFirstTrack returns undefined

### ISSUE THREAD

**Issue by tomas-berg** [medooze/semantic-sdp-js#8]
StreamInfo::getFirstTrack returns `undefined`
There is no track property.
```javascript
getFirstTrack(media) {
    for(let track of this.tracks.values())
        {
            if (track.getMedia().toLowerCase()===media.toLowerCase())
                return this.track;
        }
        return this.null;
    }
```
Please, take a look.

**Comment by notedit** [comment]
I don't think it is a bug.  please check your StreamInfo.

**Comment by murillo128** [comment]
those this.track and this.null seems wrong to me, will check them later.

**Comment by murillo128** [comment]
Thanxs for the fix!

New version published to npm.

Best regards
Sergio
